### ISSUE TITLE
[pdpix] `wait()` and `wait_any()` System Calls Should Take a Time Out

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#61]
Description
-------------

We should provide alternative versions for `wait()` and `wait_any()`, which would time out after some time has elapsed and no asynchronous operation has completed. These system calls would enable applications to not block indefinitely.

Proposed Solution
---------------------

Introduce the following alternative versions for `wait()` and `wait_any()`:

- [x] `timedwait()` - Waits for an asynchronous I/O operation to complete or a timeout to expire. (3a2bfcd437aa812c5aeb2f38798e4ea45038bb48)
- [ ] `timedwait_any()` - Waits for the first asynchronous I/O operation in a list to complete or a timeout to expire.

**Comment by BrianZill** [comment]
I'm curious as to why this changed from adding a timeout value to `wait()` and `wait_any()` to having additional `timedwait()` and `timedwait_any()` calls.  Most APIs I'm familiar with have just the call that includes the timeout value (which is optional in some way, depending upon the language could be non-existent or have a special value(s) to mean infinite or immediate).

**Comment by ppenna** [comment]
@BrianZill Linux and POSIX do feature multiple designs for exposing this same mechanism. For instance, the abstime approach that I proposed is used by [`pthread_cond_timedwait()`](https://pubs.opengroup.org/onlinepubs/9699919799/nframe.html).

**Comment by BrianZill** [comment]
These links you've been posting lately to the Open Group don't work properly, at least for me.  They end up opening some landing page, and not the page for the call you're referencing.  I think **[this](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_timedwait.html)** is the actual link you meant.

Back to the point we're discussing here, the entirety of pthreads is an alternative API.  For our main API, I would prefer that we follow the long-established precedent of `select()`, which doesn't have a separate API call for specifying a timeout.  Instead, `select()` allows one to provide a timeout if one wants one, otherwise you can just not provide that parameter.
